#!/usr/bin/env node
// Extracts only the brand icons the site uses from simple-icons into a tiny generated file.
// Run: node scripts/gen-icons.mjs
import * as si from "simple-icons";
import { writeFileSync } from "node:fs";

const slugs = [
  "python", "openjdk", "typescript", "react", "nextdotjs", "springboot", "junit5", "gatling",
  "googlegemini", "modelcontextprotocol", "tensorflow", "nvidia", "databricks", "apachespark",
  "pandas", "googlebigquery", "googlecloud", "docker", "kubernetes", "sonarqubeserver", "vercel",
  "cursor", "git", "postgresql", "cplusplus", "yolo", "ieee",
];
const out = {};
for (const s of slugs) {
  const icon = si["si" + s.charAt(0).toUpperCase() + s.slice(1)];
  if (!icon) throw new Error("missing icon " + s);
  out[s] = { title: icon.title, path: icon.path };
}
writeFileSync(
  new URL("../src/content/icons.generated.ts", import.meta.url),
  `// Generated by scripts/gen-icons.mjs from simple-icons (CC0). Do not edit by hand.\nexport const ICONS = ${JSON.stringify(out, null, 2)} as const;\nexport type IconSlug = keyof typeof ICONS;\n`,
);
console.log("wrote", Object.keys(out).length, "icons");
